#! /bin/sh

name=cups
version=2.4.14
revision=1
tarball_url="https://github.com/OpenPrinting/cups/releases/download/v${version}/cups-${version}-source.tar.gz"
tarball_sha512="c6d46b737e2fdf37a429947bc5cc3d752785187aa339bd6de94733576aead29929ae510f960c9842cb7ddc86697d7841e5aa6b9d9c9dece907a2b8f468d038a0"
imagedeps="build-essential xdg-utils"
hostdeps="gcc binutils pkg-config"
deps="core-libs libiconv zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
	cp -r "${source_dir}/." "."

        CFLAGS="$TARGET_CFLAGS -Wno-error=implicit-function-declaration" \
        LDFLAGS="$TARGET_LDFLAGS" \
    autotools_configure_noflags \
        --with-rcdir=/tmp/cupsinit \
        --with-docdir=/usr/share/cups/doc \
        --disable-dbus \
        --disable-gssapi \
        --disable-pam \
        --disable-browsing \
        --with-tls=no \
        --with-components=libcups

    sed -i s/-Werror//g Makedefs
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
