#! /bin/sh

name=iana-etc
version=20250929
revision=1
tarball_url="https://github.com/Mic92/iana-etc/releases/download/${version}/iana-etc-${version}.tar.gz"
tarball_blake2b="523a9769395255e6b433941511d7cb749db7d33e4d46bfea7c39f93ca0b44854682209844cb46d2dc95f930380912caa4dcfe0c05b126f5e6f72e6296b63445b"

package() {
    mkdir -p ${dest_dir}/etc
    cp -r ${source_dir}/{services,protocols} ${dest_dir}/etc
}
