#! /bin/sh

name=kernel
skip_pkg_check=yes
version=0.1
revision=1
source_dir="kernel"
source_allow_network="yes"
imagedeps="build-essential nasm"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure_noflags \
        -Doptimization=0 \
        -Db_sanitize=undefined
        # -Db_lto=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
