#! /bin/sh

name=libconfig
version=1.8.1
revision=1
tarball_url="https://github.com/hyperrealm/libconfig/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="96e6da09e8efdd6091edfe58cbc860296e6c484257ea95df95eea3c103fc03a46159136483d35ac4bf25ab6284d8284a1bd988d8499eb057d6226ac4ae7e950a"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen_reconf
}

configure() {
    autotools_configure \
        --disable-doc
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
