#! /bin/sh

name=linux-headers
version=6.16.6
revision=1
tarball_url="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.xz"
tarball_sha512="018c9ab624cd3f1d2d990e86194fafd79834ddeb1c4f30e56fa09f3b381fbffd564fef147ce1f443541feb40c871e749dc49f1ff183a691795122985f0ca0288"
imagedeps="build-essential rsync"

build() {
	cp -rp ${source_dir}/* .
}

package() {
	make headers_install ARCH=${JINX_ARCH} INSTALL_HDR_PATH=${dest_dir}/${prefix}/
}
