#! /bin/sh

name=mangohud
version=0.8.1
revision=1
tarball_url="https://github.com/flightlessmango/MangoHud/releases/download/v${version}/MangoHud-v${version}-Source.tar.xz"
tarball_blake2b="d817531618d51638adef441c013c02ad0f9b6d5b45d97693e26ce518b3a16c0a096f87add32137b422645993bb0280047f24bec2d998ad4733383008f4f5426b"
imagedeps="python3-mako glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs mesa libxkbcommon"

configure() {
    meson_configure \
        -Dwith_nvml=disabled \
        -Dwith_xnvctrl=disabled \
        -Dwith_x11=enabled \
        -Dwith_wayland=disabled \
        -Dwith_dbus=disabled \
        -Ddynamic_string_tokens=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
