#! /bin/sh

name=mesa
version=25.2.1
revision=2
git_url="https://gitlab.freedesktop.org/mesa/mesa.git"
commit=d6e3b017b2e38131a4918624c9c3c2792f477a96
imagedeps="python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm-libs spirv-tools vulkan-icd-loader libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Dllvm=enabled \
        -Dzstd=enabled \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dgallium-extra-hud=true \
        -Dgallium-rusticl=false \
        -Dvulkan-drivers=swrast \
        -Dvulkan-layers=overlay \
        -Dvideo-codecs=all_free
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
