#! /bin/sh

name=mtdev
version=1.1.7
revision=2
tarball_url="https://bitmath.org/code/mtdev/mtdev-${version}.tar.gz"
tarball_blake2b="3170de9b83e996ea75fc8530de1d33dbc45d818dbf2b7efb30a1d40981ea48e6b30b572f7791ca0375428464cf6c34e647ebf35ef057abc52d08af2ee333de95"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
