#! /bin/sh

name=openjdk17
version=17.0.17+7
revision=1
tarball_url="https://github.com/openjdk/jdk17u/archive/refs/tags/jdk-${version}.tar.gz"
tarball_sha512="10b82e3547385ab69856b6549b34356c96377a6d5463df0b26ec00b335761ff4904354bf613cbfd4e65b62a22cd6ae1d60f0ecea672205def685db209f97cc25"
imagedeps="build-essential zip unzip file openjdk-17-jdk"
hostdeps="gcc autoconf pkg-config"
deps="core-libs alsa-lib cups freetype2 fontconfig libpng libjpeg-turbo zlib libx11 libxext libxi libxrandr libxrender libxt libxtst xorg-proto libiconv libffi"
allow_network="yes"

prepare() {
    autotools_recursive_regen

    chmod +x configure
}

configure() {
    ${source_dir}/configure \
		--openjdk-target=${OS_TRIPLET} \
        --with-sysroot=${sysroot_dir} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --disable-ccache \
        --disable-precompiled-headers \
        --disable-warnings-as-errors \
        --enable-full-docs=no \
        --with-debug-level=slowdebug \
        --with-extra-cflags="-fpermissive -Wno-error=int-conversion -Wno-error=implicit-function-declaration -Wno-error=builtin-declaration-mismatch" \
        --with-boot-jdk="/usr/lib/jvm/java-17-openjdk-amd64" \
        --with-freetype=system \
        --with-libjpeg=system \
        --with-libpng=system \
        --with-zlib=bundled
}

build() {
    make JOBS=${parallelism} product-images
}

package() {
    mkdir -p images/jdk/.systemPrefs
    touch images/jdk/.systemPrefs/.system.lock
    touch images/jdk/.systemPrefs/.systemRootModFile
    mkdir -p "${dest_dir}/usr/lib/jvm"
    cp -pPr images/jdk "${dest_dir}/usr/lib/jvm/java-17-openjdk"
}