#! /bin/sh

name=vulkan-headers
version=1.4.327
revision=1
tarball_url="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v${version}/Vulkan-Headers-${version}.tar.gz"
tarball_blake2b="e5d6127f00167ed49a431341495675ebc93ea6e4d28c49339adf6645e9252fa52e49f03ed3a0eabdb207e0ff16870bcd762b8f05288c8e4daaf3b9c6f68c36ff"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
