#! /bin/sh

name=vulkan-icd-loader
version=1.4.327
revision=1
tarball_url="https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v${version}/Vulkan-Loader-${version}.tar.gz"
tarball_blake2b="84a769bf7d5d730e50b6eea34e1ea26cb289bc9ca7c3ed97f302299dfaa5997d2624c097dd37695b4e8717f03debe8c407a8c56d8bc4e9a6998fac0048aab147"
hostdeps="gcc pkg-config"
deps="core-libs vulkan-headers libxcb libx11 libxrandr"

configure() {
    cmake_configure \
        -DCMAKE_SKIP_RPATH=TRUE \
        -DBUILD_WSI_WAYLAND_SUPPORT=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
