#! /bin/sh

name=vulkan-tools
version=1.4.327
revision=1
tarball_url="https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="a8a1b67393c817cfe685d6123129385f9f72691d41275647612c1c37f219cb7b812aac2d1368c723463c2e4dd9dc33fe20d3942472b958e03784067446d50d7d"
hostdeps="gcc pkg-config"
deps="core-libs mesa"

configure() {
    cmake_configure \
        -DCMAKE_SKIP_RPATH=TRUE \
        -DBUILD_ICD=OFF \
        -DBUILD_WSI_WAYLAND_SUPPORT=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
