#! /bin/sh

name=xf86-input-evdev
repology_id=xdrv:evdev
version=2.11.0
revision=1
tarball_url="https://gitlab.freedesktop.org/xorg/driver/xf86-input-evdev/-/archive/xf86-input-evdev-${version}/xf86-input-evdev-xf86-input-evdev-${version}.tar.gz"
tarball_blake2b="f2fcab4baa8d362ac2e8dad01fd5cb5bec778b64d6147c9b47284237f66e461a18c0c2a0d17d382c37c8901a193c0759176ec221d700174bf211a1f8047d0189"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-server xorg-util-macros libx11 libevdev mtdev"

prepare() {
    autotools_recursive_regen_reconf
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    rm -rf "${dest_dir}"/sysroot # not sure where this comes from

    post_package_strip
}
